### ISSUE TITLE
Updates with GGally

### ISSUE THREAD

**Issue by schloerke** [OakleyJ/SHELF#1]
Hi Jeremy,

I'm submitting a new update for GGally today to match the update with ggplot2.  

I'm breaking your Multivariate-normal-copula.Rmd vignette, but it's a quick fix.  Feel free to format the code below how you like, but the `columnLabels` are now paired with a `labeller` argument (similar to ggplot2).

Thank you,
Barret

```r
GGally::ggpairs(
  data.frame(theta),
  lower = list(
    continuous = GGally::wrap(
      GGally::ggally_points, 
      color = "red",
      alpha = 0.1
    )
  ),
  columnLabels = c("X[1]", "X[2]", "X[3]"),
  labeller = ggplot2::label_parsed
)
```

**Comment by OakleyJ** [comment]
Thanks, Barret. I've implemented this in 1.2.2.
