### ISSUE TITLE
still on copulaSample and multiple experts and multiple endpoints.

### ISSUE THREAD

**Issue by dkarletsos** [OakleyJ/SHELF#11]
Hi @OakleyJ, I have just one question regarding your answer in this thread: https://github.com/OakleyJ/SHELF/issues/8#issuecomment-1573514662_

Quoting you:

> But if you do want to generate a sample for each expert, hopefully it's not too painful to do this manually, e.g. (continuing your example)
> 
> ```
> x <- array(dim = c(100, 3, 2))
> for(i in 1:2){
>   x[, , i] <- copulaSample(myfit1, myfit2, myfit3, cp=quad.probs, n=100, ex = i)
> }
> ```

myfit1 <- fitdist(v1, p1, 0, 1), and v1 can be a matrix with one column per expert, in the current version.

If I had to implement this approach, I understand that there would need to be 
myfit1_expert1 <- fitdist(v1[, 1], p1, 0, 1), 
myfit1_expert2 <- fitdist(v1[, 2], p1, 0, 1)
etc.

Does this make sense to you?

**Comment by OakleyJ** [comment]
You can still do this with one elicitation object per variable (multiple experts within each elicitation object). Here's an example:

```
library(SHELF)

# Suppose experts 1 and expert 2 provide quartiles for two quantities
p1 <- c(0.25, 0.5, 0.75)

# one column per expert in v1 and v2
v1 <- matrix(c(10, 20, 30, 45, 50, 60), 3, 2)
v2 <- matrix(c(25, 30, 40, 70, 80, 90), 3, 2)
myfit1 <- fitdist(v1, p1, lower = 0, upper = 100)
myfit2 <- fitdist(v2, p1, lower = 0, upper = 100)


quad.probs <- array(0, dim  = c(2, 2, 2))
quad.probs[1, 2, 1] <- 0.1 # Negative correlation in expert 1's beliefs
quad.probs[1, 2, 2] <- 0.9 # Positive correlation in expert 2's beliefs

x <- array(dim = c(1000, 2, 2))
for(i in 1:2){
  x[, , i] <- copulaSample(myfit1, myfit2,
                           cp=quad.probs[, , i],
                           n=1000, ex = i,
                           d = c("beta", "beta"))
}

plot(x[, 1, 1], x[, 2, 1]) # plot expert 1 sample
abline(v = 20, h = 30) # plot expert 1 elicited medians

plot(x[, 1, 2], x[, 2, 2]) # plot expert 2 sample
abline(v = 50, h = 80) # plot expert 2 elicited medians
```
