### ISSUE TITLE
fitdist in example needs to import MASS

### ISSUE THREAD

**Issue by evelynmitchell** [OakleyJ/SHELF#2]
I just installed SHELF from cran.

When I ran the Example in the SHELF help page, it failed on;
> p <- c(0.25, 0.5, 0.75)
> myfit <- fitdist(vals = v, probs = p, lower = 0, upper = 100)
Error in fitdist(vals = v, probs = p, lower = 0, upper = 100) : 
  could not find function "fitdist"

I believe fitdist has been superceded by fitdistrplus. 

The example needs to include:
library(MASS) to run.

I found SHELF through https://arxiv.org/abs/1708.09823

I can make a patch if you like.

Package:	 SHELF
Type:	 Package
Version:	 1.2.3
Date:	 2017-02-10
License:	 GPL-2 | GPL-3
Into the most recent Rstudo:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) RStudio Safari/538.1 Qt/5.4.0

When I ran the Example in the SHELF help page, it failed on;
> p <- c(0.25, 0.5, 0.75)
> myfit <- fitdist(vals = v, probs = p, lower = 0, upper = 100)
Error in fitdist(vals = v, probs = p, lower = 0, upper = 100) : 
  could not find function "fitdist"

**Comment by OakleyJ** [comment]
I think you've missed off the `library(SHELF)` command at the start. (I didn't specify that in the example).

Cheers,
Jeremy
