### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TimeWz667** [OakleyJ/SHELF#3]
Hi, 
The package was pretty lovely and important in health research. I appreciated. Could you please check and fix the license in this package? As I know, the GPL3 and GPL2 are not compatible, and dual licensing is not allowed for them. This issue keeps people from using SHELF.

**Comment by OakleyJ** [comment]
I confess I'm not too knowledgeable about licensing...but are you sure "GPL-2 | GPL-3" isn't allowed? R itself has the same license: 

https://www.r-project.org/Licenses/

(as do some of the packages imported by SHELF). My understanding from here

https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#VersionTwoOrLater

is that "GPL-2 | GPL-3" means that any additional permissions from GPL-3 are allowed, but any tighter requirements from GPL-3 do not apply, as long as GPL-2 is adhered to.

**Comment by TimeWz667** [comment]
Thanks. It is confusing by itself. There are many ways to interpret "GPL-2 | GPL-3". I raised the issue just in case of offending your copyright unintentionally. 

Could you add a license file to the repository?

**Comment by OakleyJ** [comment]
License file added.
