### ISSUE TITLE
plotfit expert labels

### ISSUE THREAD

**Issue by mdwhitby** [OakleyJ/SHELF#5]
Is there a way to use the same expertnames from the elicitation object (generated by fitdist) in the graph of a fitted density function graph generated by plotfit?

Currently, I have an elicitation object that starts like this:
$Normal
          mean            sd
A 0.4500000000 0.05940914749
B 0.0002499956 0.00003704688
C 0.3000000000 0.07803041461
E 0.1615382343 0.13466064720

But the graph uses expertnames of A, B, C, D.

Thanks

**Comment by OakleyJ** [comment]
I've updated the code to fix this. If you specify your expertnames in fitdist(), it should work:

v <- matrix(c(20,30,50,55,60,70),3,2)
p <- c(0.25,0.5,0.75)
myfit <- fitdist(vals=v, probs=p, lower=0,
                 expertnames = c("Z1", "A1"))
plotfit(myfit)

You should also now be able to edit expert names (by clicking on them in the table) in the elicitMultiple() app.
