### ISSUE TITLE
mvrnorm not invariant to flipping of eigenvectors

### ISSUE THREAD

**Issue by stefanoborini** [OakleyJ/SHELF#7]
We are trying to fix a reproducibility bug and we observed the following. It's not a problem of SHELF, but something that is in MASS::mvrnorm, but has consequences on the results of SHELF::copulaSample.

At line 70 we have the following line:

```
     z <- MASS::mvrnorm(n, mu = rep(0, n.vars), r)   
```

Now what we noticed is that this function performs an eigen call:

```
mvrnorm <-                                                                                
    function(n = 1, mu, Sigma, tol=1e-6, empirical = FALSE, EISPACK = FALSE)              
{                                                                                         
    p <- length(mu)                                                                       
    if(!all(dim(Sigma) == c(p,p))) stop("incompatible arguments")                         
    if(EISPACK) stop("'EISPACK' is no longer supported by R", domain = NA)                
    eS <- eigen(Sigma, symmetric = TRUE)                                                  
    ev <- eS$values                                                                       
    if(!all(ev >= -tol*abs(ev[1L]))) stop("'Sigma' is not positive definite")             
    X <- matrix(rnorm(p * n), n)                                                          
    if(empirical) {                                                                       
        X <- scale(X, TRUE, FALSE) # remove means                                         
        X <- X %*% svd(X, nu = 0)$v # rotate to PCs                                       
        X <- scale(X, FALSE, TRUE) # rescale PCs to unit variance                         
    }                                                                                     
    X <- drop(mu) + eS$vectors %*% diag(sqrt(pmax(ev, 0)), p) %*% t(X)                    
    nm <- names(mu)                                                                       
    if(is.null(nm) && !is.null(dn <- dimnames(Sigma))) nm <- dn[[1L]]                     
    dimnames(X) <- list(nm, NULL)                                                         
    if(n == 1) drop(X) else t(X)                                                          
}             
```

The problem happens due to the fact that the eigen call may return eigenvectors that are multiplied by -1 (as any constant is irrelevant for the eigenvectors, but they are orthonormal and therefore a coefficient of -1 is possible). However, the presence of this coefficient has consequences on the resulting X evaluation, and therefore on the result of mvrnorm, and therefore on the copulaSample.

We noticed wildly different results on this when performing the same calculation with the same seed on different machines, just because the eigen function has this mathematically arbitrary behavior, but it has consequences on the result.

Do you have any experience with this to suggest us how to ensure a consistent calculation? MASS does not have an issue reporting dialog, and you might know more about this lack of invariance. I am not a statistician, so I am unable to judge on the correctness of all of this.

Thanks.

**Comment by OakleyJ** [comment]
I don't know if I'll be able to help with this, but could you post an example of getting different results, so I can see what you have done?

**Comment by stefanoborini** [comment]
This script gives you an idea

```
p1 <- c(0.1, 0.5, 0.90)
v1 <- c(0.01, 0.10, 0.22)
v2 <- c(0.04, 0.12, 0.26)
v3 <- c(0.04, 0.16, 0.36)
myfit1 <- fitdist(v1, p1, -1, 1)
myfit2 <- fitdist(v2, p1, -1, 1)
myfit3 <- fitdist(v3, p1, -1, 1)
quad.probs <- matrix(0, 3, 3)
quad.probs[1, 2] <- 0.80
quad.probs[1, 3] <- 0.40
quad.probs[2, 3] <- 0.50
theta <- copulaSample(myfit1, myfit2, myfit3, cp=quad.probs, n=10, d=rep("normal", 3))
print(theta)
```

On my machine we get:

```
$ Rscript trt_sims.R 
Using environment default (R version: 4.0.4, platform: x86_64-apple-darwin17.0)
        [,1]       [,2]       [,3]
[1,] 0.08434585 0.13366609 0.28616305
[2,] 0.17541647 0.18907682 0.09855172
[3,] 0.07561670 0.10665462 0.35792808
[4,] 0.12121336 0.17257691 0.21430461
[5,] 0.07748259 0.08177733 0.14168751
[6,] 0.14547423 0.15908413 0.13153111
[7,] 0.11973107 0.20865161 0.19258941
[8,] 0.17987279 0.14188643 0.24223206
[9,] 0.31895857 0.36426611 0.06844026
[10,] 0.14001745 0.19934395 0.10147010
```

On a M1 machine we get:

```
          [,1]        [,2]      [,3] 
[1,]  0.12620061  0.17274584 0.2641619 
[2,]  0.02896866  0.05233866 0.1755326 
[3,]  0.16882945  0.19368725 0.3089304 
[4,]  0.07242747  0.12702558 0.2399491 
[5,]  0.13970390  0.13987329 0.1089806 
[6,]  0.06498935  0.08393550 0.1738383 
[7,]  0.03345062  0.12809166 0.2379431 
[8,]  0.10787670  0.07466377 0.2800771 
[9,] -0.14206482 -0.06619090 0.3107790 
[10,]  0.02007940  0.08735793 0.1645160
```

The reason seems to be that the eigen() function in mvrnorm can return eigenvectors that can swap signs. From the mathematical point of view, there's no difference in having an eigenvector or -1 * eigenvector. Both solve the eigen() problem. Which one you get depends on numerical issues on the machine and the algorithm used. However, they do have a difference when it's time to do math with it.

**Comment by stefanoborini** [comment]
We found this document that may be relevant to the issue

https://www.osti.gov/servlets/purl/920802

**Comment by OakleyJ** [comment]
The eigen() function is being applied to a correlation matrix which will be positive definite (or at least non-negative definite if you have supplied concordance probabilities of 0 or 1), and so the eigenvalues shouldn't be negative. So I'm not sure this is the issue. Do your two machines give different results if you do

```
quad.probs <- matrix(0, 3, 3)
quad.probs[1, 2] <- 0.80
quad.probs[1, 3] <- 0.40
quad.probs[2, 3] <- 0.50

cp <- quad.probs
r <- sin(2 * pi * cp / 2 - pi / 2)
diag(r) <- 1
r[lower.tri(r)] <- r[upper.tri(r)]

eigen(r, symmetric = TRUE)
```
which for me produces the result
```
eigen() decomposition
$values
[1] 1.8660254 1.0000000 0.1339746

$vectors
           [,1]      [,2]       [,3]
[1,] -0.7071068 0.0000000  0.7071068
[2,] -0.6605596 0.3568221 -0.6605596
[3,]  0.2523113 0.9341724  0.2523113
```
And what seed did you use in your example?

**Comment by stefanoborini** [comment]
It's not the eigenvalues the problem. it's the eigen**vectors**. You can equally have, for the first column 

```(-0.7071068, -0.6605596, 0.2523113)```

or 

```(0.7071068, 0.6605596, -0.2523113)```

They are mathematically equivalent, but they are not equivalent for the following code that uses these vectors.

**Comment by OakleyJ** [comment]
Sorry, I get you now. But could you just show me what you got for the two decompositions (and the seed you used).

**Comment by stefanoborini** [comment]
@dkarletsos do you have the information on this?

**Comment by dkarletsos** [comment]
On my machine (`R.version$arch == "aarch64"`), using `set.seed(420)`, I get this:

```
eigen() decomposition
$values
[1] 1.8660254 1.0000000 0.1339746

$vectors
           [,1]      [,2]       [,3]
[1,]  0.7071068 0.0000000  0.7071068
[2,]  0.6605596 0.3568221 -0.6605596
[3,] -0.2523113 0.9341724  0.2523113
```

**Comment by stefanoborini** [comment]
@dkarletsos

> On my machine (`R.version$arch == "aarch64"`), using `set.seed(420)`, I get this:
> 
> ```
> eigen() decomposition
> $values
> [1] 1.8660254 1.0000000 0.1339746
> 
> $vectors
>            [,1]      [,2]       [,3]
> [1,]  0.7071068 0.0000000  0.7071068
> [2,]  0.6605596 0.3568221 -0.6605596
> [3,] -0.2523113 0.9341724  0.2523113
> ```

What do you get on the intel linux? I guess the same as the macos intel.

**Comment by stefanoborini** [comment]
Yes, confirmed same result on the intel linux and the intel macos.

**Comment by OakleyJ** [comment]
I've tried switching from the eigendecomposition to the Cholesky - think this should fix it? I've updated `copulaSample()`

Could you check the following?

```
set.seed(420)
p1 <- c(0.1, 0.5, 0.90)
v1 <- c(0.01, 0.10, 0.22)
v2 <- c(0.04, 0.12, 0.26)
v3 <- c(0.04, 0.16, 0.36)
myfit1 <- fitdist(v1, p1, -1, 1)
myfit2 <- fitdist(v2, p1, -1, 1)
myfit3 <- fitdist(v3, p1, -1, 1)
quad.probs <- matrix(0, 3, 3)
quad.probs[1, 2] <- 0.80
quad.probs[1, 3] <- 0.40
quad.probs[2, 3] <- 0.50

theta <- copulaSample(myfit1, myfit2, myfit3, cp=quad.probs, n=100000, d=rep("normal", 3))

head(theta)
```

for which I get

```
           [,1]       [,2]       [,3]
[1,] 0.12574193 0.13853805 0.34148329
[2,] 0.02826934 0.01719915 0.08135068
[3,] 0.15232677 0.17332390 0.20391862
[4,] 0.07882287 0.12609635 0.14500901
[5,] 0.13628443 0.16092717 0.08419185
[6,] 0.06241427 0.07814337 0.17712995
```

and also

```
> mean((theta[, 1] > 0.1 & theta[, 2] > 0.12) | (theta[, 1] < 0.1 & theta[, 2] < 0.12))
[1] 0.80009
> mean((theta[, 1] > 0.1 & theta[, 3] > 0.16) | (theta[, 1] < 0.1 & theta[, 3] < 0.16))
[1] 0.40521
> mean((theta[, 2] > 0.12 & theta[, 3] > 0.16) | (theta[, 2] < 0.12 & theta[, 3] < 0.16))
[1] 0.5067
```

**Comment by stefanoborini** [comment]
@OakleyJ Thanks, we'll try it out asap.

@dkarletsos we'll have to install it from github, I'll show you how to do so.

**Comment by dkarletsos** [comment]
@OakleyJ,  I get the same results as you now - seems to be working.

```
set.seed(420)

p1 <- c(0.1, 0.5, 0.90)
v1 <- c(0.01, 0.10, 0.22)
v2 <- c(0.04, 0.12, 0.26)
v3 <- c(0.04, 0.16, 0.36)
myfit1 <- fitdist(v1, p1, -1, 1)
myfit2 <- fitdist(v2, p1, -1, 1)
myfit3 <- fitdist(v3, p1, -1, 1)
quad.probs <- matrix(0, 3, 3)
quad.probs[1, 2] <- 0.80
quad.probs[1, 3] <- 0.40
quad.probs[2, 3] <- 0.50

theta <- SHELF::copulaSample(myfit1, myfit2, myfit3, cp=quad.probs, n=100000, d=rep("normal", 3))

head(theta)

           [,1]       [,2]       [,3]
[1,] 0.12574193 0.13853805 0.34148329
[2,] 0.02826934 0.01719915 0.08135068
[3,] 0.15232677 0.17332390 0.20391862
[4,] 0.07882287 0.12609635 0.14500901
[5,] 0.13628443 0.16092717 0.08419185
[6,] 0.06241427 0.07814337 0.17712995
```
and:
```
> mean((theta[, 1] > 0.1 & theta[, 2] > 0.12) | (theta[, 1] < 0.1 & theta[, 2] < 0.12))
[1] 0.80009
> mean((theta[, 1] > 0.1 & theta[, 3] > 0.16) | (theta[, 1] < 0.1 & theta[, 3] < 0.16))
[1] 0.40521
> mean((theta[, 2] > 0.12 & theta[, 3] > 0.16) | (theta[, 2] < 0.12 & theta[, 3] < 0.16))
[1] 0.5067
```

**Comment by stefanoborini** [comment]
Confirmed same results also on the mac intel:

> head(theta)
           [,1]       [,2]       [,3]
[1,] 0.12574193 0.13853805 0.34148329
[2,] 0.02826934 0.01719915 0.08135068
[3,] 0.15232677 0.17332390 0.20391862
[4,] 0.07882287 0.12609635 0.14500901
[5,] 0.13628443 0.16092717 0.08419185
[6,] 0.06241427 0.07814337 0.17712995

Very good @OakleyJ. Thanks!

**Comment by OakleyJ** [comment]
Great! Thanks for checking, and thanks for letting me know about the problem.
