### ISSUE TITLE
copulaSample failing with more than one expert elicitation

### ISSUE THREAD

**Issue by dkarletsos** [OakleyJ/SHELF#8]
The copulaSample function fails when using multiple experts (e.g. v1 is a matrix of elicited values, one column per expert)
```
p1 <- matrix(c(0.25, 0.5, 0.75, 
                0.25, 0.5, 0.75), 3, 2)
 v1 <- matrix(c(0.5, 0.55, 0.6,
                0.5, 0.55, 0.6), 3, 2)
 v2 <- matrix(c(0.22, 0.3, 0.35,
                0.22, 0.3, 0.35), 3, 2)
 v3 <- matrix(c(0.11, 0.15, 0.2,
                0.11, 0.15, 0.2), 3, 2)
 myfit1 <- fitdist(v1, p1, 0, 1)
 myfit2 <- fitdist(v2, p1, 0, 1)
 myfit3 <- fitdist(v3, p1, 0, 1)
 quad.probs <- matrix(0, 3, 3)
 quad.probs[1, 2] <- 0.4
 quad.probs[1, 3] <- 0.4
 quad.probs[2, 3] <- 0.3
 copulaSample(myfit1, myfit2, myfit3, cp=quad.probs, n=100, d=NULL)
```

```
Error in `[.data.frame`(feedback(elicitation.fits[[i]], quantiles = p[, : 
undefined columns selected
```

The single-expert example included in the documentation works as expected:
```
#' \dontrun{
#' p1 <- c(0.25, 0.5, 0.75)
#' v1 <- c(0.5, 0.55, 0.6)
#' v2 <- c(0.22, 0.3, 0.35)
#' v3 <- c(0.11, 0.15, 0.2)
#' myfit1 <- fitdist(v1, p1, 0, 1)
#' myfit2 <- fitdist(v2, p1, 0, 1)
#' myfit3 <- fitdist(v3, p1, 0, 1)
#' quad.probs <- matrix(0, 3, 3)
#' quad.probs[1, 2] <- 0.4
#' quad.probs[1, 3] <- 0.4
#' quad.probs[2, 3] <- 0.3
#' copulaSample(myfit1, myfit2, myfit3, cp=quad.probs, n=100, d=NULL)
#' }
```

**Comment by OakleyJ** [comment]
I've updated the function with a (partial!) solution. There is now an extra argument (ex = 1 by default) that will select a single expert's judgements, from which the sample is generated.

Continuing your multiple expert example, you would now do

```copulaSample(myfit1, myfit2, myfit3, cp=quad.probs, n=100, d=NULL, ex = 1)```

I guess you wanted ```copulaSample()``` to produce samples for all experts simultaneously. I've chosen _not_ to do that, partly because I don't want the output format to change, but also because I think the use case isn't quite right here: if you've got different judgements from the experts, you might also expect each expert to have different concordance probabilities, so that ```quad.probs``` is different for each expert. 

But if you do want to generate a sample for each expert, hopefully it's not too painful to do this manually, e.g. (continuing your example)

```
x <- array(dim = c(100, 3, 2))
for(i in 1:2){
  x[, , i] <- copulaSample(myfit1, myfit2, myfit3, cp=quad.probs, n=100, ex = i)
}
```

is this all ok?

**Comment by dkarletsos** [comment]
Thank you @OakleyJ. Could you please make a release of this on CRAN? If so, do you know when we can expect it to be available? Thanks

**Comment by dkarletsos** [comment]
Actually, taking a closer look, I do not think this resolves the problem. If we leave as it is, the package has some important internal inconsistency. Let me illustrate this.

The function fitdist can take the vals argument in the form of vector or matrix as per documentation of fitdist.R, line 10. If it is a matrix, each column represents a different expert.

Now, in the example below, fitdist is used to produce the objects myfit1, which is then used by the downstream function elicitCopula. However, you are saying that in this specific case, the downstream function elicitCopula will not work anymore if the vals argument in fitdist was a matrix.

This of course contradicts the original definition and the documentation of the fitdist function.

```
#' \dontrun{
#' p1 <- c(0.25, 0.5, 0.75)
#' v1 <- c(0.5, 0.55, 0.6)
#' v2 <- c(0.22, 0.3, 0.35)
#' v3 <- c(0.11, 0.15, 0.2)
#' myfit1 <- fitdist(v1, p1, 0, 1)
#' myfit2 <- fitdist(v2, p1, 0, 1)
#' myfit3 <- fitdist(v3, p1, 0, 1)
#' quad.probs <- matrix(0, 3, 3)
#' quad.probs[1, 2] <- 0.4
#' quad.probs[1, 3] <- 0.4
#' quad.probs[2, 3] <- 0.3
#' copulaSample(myfit1, myfit2, myfit3, cp=quad.probs, n=100, d=NULL)
#' }
```

Is my interpretation correct?

Thanks

**Comment by OakleyJ** [comment]
I think ```copulaSample()``` still works ok in each case - if you have an example where it doesn't, please let me know.

But there is something of an inconsistency in fitdist anyway! The inputs require one column per expert, but the outputs all use one row per expert. For some reason, I'd decided I needed fitdist to work if given the outputs (```$vals``` and ```$probs```)  as inputs. I'd put in a hack to make it work in that case, but I'm now pretty sure that was a really bad idea!

So, I've got a bit of tidying/testing to do before a CRAN update.

**Comment by OakleyJ** [comment]
All seems to work ok...I've updated on CRAN now.
