### ISSUE TITLE
Specifying the y-axis scale

### ISSUE THREAD

**Issue by CMzyece** [OakleyJ/SHELF#9]
Hello Jeremy,

Is there a way of specifying an upper and lower bound on the y-axis for beta plots generated in the SHELF R package version 1.9.0?

**Comment by OakleyJ** [comment]
Is this an option you wanted in the plotfit() command, or did you want something available in the apps, e.g. elicit()?

**Comment by CMzyece** [comment]
Sorry I didnt specify. That's in plotfit.

**Comment by CMzyece** [comment]
Hello Jeremy,

Sorry I didnt specify. This is in plotfit.

Chisha
________________________________

**Comment by OakleyJ** [comment]
Sorry for the very slow response! Now implemented: optional arguments yl and yu added to plotfit(). e.g.

```
v <- matrix(c(30, 40, 50, 20, 25, 35), 3, 2)
p <- c(0.25, 0.5, 0.75)
myfit <- fitdist(vals = v, probs = p, lower = 0, upper = 100)
plotfit(myfit)
```

Then change y-axis limits with

```
plotfit(myfit, yu = 0.1)
```

and if you wanted to for some reason

```
plotfit(myfit, yl = -0.1, yu = 0.1)
```
